In [9]:
from collections import defaultdict
import torch

x = torch.tensor([3, 5, 2, 3, 7, 2, 3, 1, 9, 5, 8, 6, 3, 4, 5, 2, 0])
# counts = torch.bincount(x)
# print(counts)

index_dict = defaultdict(list)
for idx, val in enumerate(x.tolist()):
    index_dict[val].append(idx)

index_dict = dict(index_dict)
print(index_dict)
# 输出: {3: [0, 3, 6], 2: [2, 5]}
batch = []
bs = 10
for i in range(bs):
    cur_dict = {}
    cur_dict['index'] = index_dict[i] if i in index_dict else []
    batch.append(cur_dict)
print(batch)

{3: [0, 3, 6, 12], 5: [1, 9, 14], 2: [2, 5, 15], 7: [4], 1: [7], 9: [8], 8: [10], 6: [11], 4: [13], 0: [16]}
[{'index': [16]}, {'index': [7]}, {'index': [2, 5, 15]}, {'index': [0, 3, 6, 12]}, {'index': [13]}, {'index': [1, 9, 14]}, {'index': [11]}, {'index': [4]}, {'index': [10]}, {'index': [8]}]


In [4]:
import torch
edge_index = [
    [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
    [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
]
index = torch.tensor([0, 1, 7, 9], dtype=torch.long)
edge_index = torch.tensor(edge_index, dtype=torch.long).T
print(edge_index)
for edge in edge_index:
    if edge[0] in index or edge[1] in index:
        print(edge)

tensor([[0, 0],
        [1, 1],
        [2, 2],
        [3, 3],
        [4, 4],
        [5, 5],
        [6, 6],
        [7, 7],
        [8, 8],
        [9, 9]])
tensor([0, 0])
tensor([1, 1])
tensor([7, 7])
tensor([9, 9])


In [16]:
import torch 
import os
root = "."
cached_data = torch.load(os.path.join(root, "processed/all_ori.pt"))
print(len(cached_data))
for data_dict in cached_data:
    print("data_dict.keys(): ", list(data_dict.keys()))
    print("data_dict['anchors']: ", data_dict['anchors'])
    # print("data_dict['wyckoff_ops']: ", data_dict['wyckoff_ops'])
    # 描述某个原子在空间群对称操作下，对应的 Wyckoff 位置的运算符集合（即对称生成的位置）
    print("data_dict['spacegroup']: ", data_dict['spacegroup'])
    print("data_dict['mp_id']: ", data_dict['mp_id'])
    # print("data_dict['cif']: ", data_dict['cif'])

    graph_arrays = data_dict["graph_arrays"]
    print("data_dict['graph_arrays'].keys(): ", list(graph_arrays.keys()))

    print("data_dict['formation_energy_per_atom']: ", data_dict['formation_energy_per_atom'])
    # 每个原子对应的形成能。定义为材料与其构成元素在最稳定单质状态下的能量差
    print("data_dict['band_gap']: ", data_dict['band_gap'])
    print("data_dict['e_above_hull']: ", data_dict['e_above_hull'])
    break

45229
data_dict.keys():  ['anchors', 'wyckoff_ops', 'spacegroup', 'mp_id', 'cif', 'graph_arrays', 'formation_energy_per_atom', 'band_gap', 'e_above_hull']
data_dict['anchors']:  [0 0 0 0 4 4 4 4]
data_dict['spacegroup']:  194
data_dict['mp_id']:  mp-10009
data_dict['graph_arrays'].keys():  ['atom_types', 'frac_coords', 'cell', 'lattices', 'lengths', 'angles', 'edge_indices', 'to_jimages', 'num_atoms']
data_dict['formation_energy_per_atom']:  -0.5750923537499997
data_dict['band_gap']:  0.8979999999999997
data_dict['e_above_hull']:  0.0


In [ ]:
import numpy as np
# Load downloaded/processed datasets
datafile = os.path.join("/home/mcw/UniGEM/qm9/temp/qm9/train.npz")
with np.load(datafile) as f:
    datasets = {key: torch.from_numpy(val) for key, val in f.items()}
print(datasets.keys())
# output:
# dict_keys(['num_atoms', 'charges', 'positions', 'index', 'A', 'B', 'C', 'mu', 'alpha', 'homo', 'lumo', 'gap', 
# 'r2', 'zpve', 'U0', 'U', 'H', 'G', 'Cv', 'omega1', 'zpve_thermo', 'U0_thermo', 'U_thermo', 'H_thermo', 'G_thermo', 'Cv_thermo'])

dict_keys(['num_atoms', 'charges', 'positions', 'index', 'A', 'B', 'C', 'mu', 'alpha', 'homo', 'lumo', 'gap', 'r2', 'zpve', 'U0', 'U', 'H', 'G', 'Cv', 'omega1', 'zpve_thermo', 'U0_thermo', 'U_thermo', 'H_thermo', 'G_thermo', 'Cv_thermo'])


In [13]:
import torch
l = torch.tensor([[1.0549, -1.6198,  0.3320]])
t = torch.tensor([[1.],[1.]])
print(l.shape)
print(t.shape)

l = l.repeat(1, 10)
print(l)
print(l.shape)
print(l.reshape(10,-1))
print(l.view(10,-1))

torch.Size([1, 3])
torch.Size([2, 1])
tensor([[ 1.0549, -1.6198,  0.3320,  1.0549, -1.6198,  0.3320,  1.0549, -1.6198,
          0.3320,  1.0549, -1.6198,  0.3320,  1.0549, -1.6198,  0.3320,  1.0549,
         -1.6198,  0.3320,  1.0549, -1.6198,  0.3320,  1.0549, -1.6198,  0.3320,
          1.0549, -1.6198,  0.3320,  1.0549, -1.6198,  0.3320]])
torch.Size([1, 30])
tensor([[ 1.0549, -1.6198,  0.3320],
        [ 1.0549, -1.6198,  0.3320],
        [ 1.0549, -1.6198,  0.3320],
        [ 1.0549, -1.6198,  0.3320],
        [ 1.0549, -1.6198,  0.3320],
        [ 1.0549, -1.6198,  0.3320],
        [ 1.0549, -1.6198,  0.3320],
        [ 1.0549, -1.6198,  0.3320],
        [ 1.0549, -1.6198,  0.3320],
        [ 1.0549, -1.6198,  0.3320]])
tensor([[ 1.0549, -1.6198,  0.3320],
        [ 1.0549, -1.6198,  0.3320],
        [ 1.0549, -1.6198,  0.3320],
        [ 1.0549, -1.6198,  0.3320],
        [ 1.0549, -1.6198,  0.3320],
        [ 1.0549, -1.6198,  0.3320],
        [ 1.0549, -1.6198,  0.3320],
    

In [ ]:
import pandas as pd
import os
dataset_folder_path = "."
dataset_cif_list=pd.read_csv(
                os.path.join(dataset_folder_path, "/all.csv")
            )["cif"].tolist()